class Verus < Formula
  desc "Tool to verify correctness of code written in Rust"
  homepage "https://github.com/verus-lang/verus"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
    regex(%r{release/v?(\d+(?:\.\d+)+\.[0-9a-f]+)}i)
  end

  depends_on "rustup"

  # Verus ships prebuilt, per-platform archives; this formula is a pure relocation
  # layer; nothing is compiled at install time. GENERATED by scripts/generate-formula.sh,
  # do not edit by hand.
  on_macos do
    on_arm do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.05.49b8806/verus-0.2026.07.05.49b8806-arm64-macos.zip"
      sha256 "4090a9ebdd3d68f1acf29bfbc83e7746c3d5c0cf9352f42a3ebc26129f7b11fa"
    end
    on_intel do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.05.49b8806/verus-0.2026.07.05.49b8806-x86-macos.zip"
      sha256 "e7d9410cee73958e9b47b71df4d4acf372296d56b4df20b2f930c1a299439082"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.05.49b8806/verus-0.2026.07.05.49b8806-x86-linux.zip"
      sha256 "cb4fe7db423fdda5e9aa77b2c3e632f8a618b6a991509283aae591f0a914d34c"
    end
  end

  def install
    # The archive expands to a single verus-<arch>-<os>/ directory, which Homebrew
    # descends into automatically, so Dir["*"] is its contents: the `verus` launcher,
    # the `z3` solver, the `vstd` standard library and the rest of the runtime. `verus`
    # locates those relative to its own path, so the whole tree must stay together;
    # we keep it in libexec and expose only the launchers via exec scripts (this also
    # avoids leaking a generic `z3` into bin and clashing with the z3 formula).
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"verus"
    bin.write_exec_script libexec/"cargo-verus"
  end

  def caveats
    <<~EOS
      Verus needs a specific rustup-managed Rust toolchain at runtime. It is not
      bundled and not installed by Homebrew. Run `verus` once and it prints the exact
      toolchain to install, for example:

        rustup install <version>-<your-target-triple>

      Homebrew installs only `rustup`; the toolchain itself lives in ~/.rustup, may be
      shared with other Rust projects, and is left in place by `brew uninstall verus`.
      To reclaim that space later:

        rustup toolchain uninstall <version>-<your-target-triple>
    EOS
  end

  test do
    # The right version landed and stayed addressable from libexec.
    assert_equal version.to_s, (libexec/"version.txt").read.strip

    # With no matching toolchain installed (the case on a clean CI runner), the relocated
    # launcher finds its bundled metadata and reports which toolchain it needs. `|| true`
    # keeps the assertion independent of the exact exit code, which on this path is passed
    # through from rustup rather than chosen by verus.
    output = shell_output("#{bin}/verus --version 2>&1 || true")
    assert_match "toolchain", output
  end
end
