class Verus < Formula
  desc "Tool to verify correctness of code written in Rust"
  homepage "https://github.com/verus-lang/verus"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
    regex(%r{release/v?(\d+(?:\.\d+)+\.[0-9a-f]+)}i)
  end

  depends_on "rustup"

  # Verus ships prebuilt, per-platform archives; this formula is a pure relocation
  # layer; nothing is compiled at install time. GENERATED by scripts/generate-formula.sh,
  # do not edit by hand.
  on_macos do
    on_arm do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.27.31579f0/verus-0.2026.07.27.31579f0-arm64-macos.zip"
      sha256 "feb4eb5e9b0ecbedc7be75fcc5894dc0d98a40579a0fb4d4d69f17eb3991f4bf"
    end
    on_intel do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.27.31579f0/verus-0.2026.07.27.31579f0-x86-macos.zip"
      sha256 "910d7156eb09e805bfd1860ebc57f19bb52931769ff530138be91cad7514e733"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/verus-lang/verus/releases/download/release/0.2026.07.27.31579f0/verus-0.2026.07.27.31579f0-x86-linux.zip"
      sha256 "7a6143e6dcd2db778314ac102c5ceeac1f7f152b028e3428798bff7170212498"
    end
  end

  def install
    # The archive expands to a single verus-<arch>-<os>/ directory, which Homebrew
    # descends into automatically, so Dir["*"] is its contents: the `verus` launcher,
    # the `z3` solver, the `vstd` standard library and the rest of the runtime. `verus`
    # locates those relative to its own path, so the whole tree must stay together;
    # we keep it in libexec and expose only the launchers via exec scripts (this also
    # avoids leaking a generic `z3` into bin and clashing with the z3 formula).
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"verus"
    bin.write_exec_script libexec/"cargo-verus"
  end

  def caveats
    <<~EOS
      Verus needs a specific rustup-managed Rust toolchain at runtime. It is not
      bundled and not installed by Homebrew. Run `verus` once and it prints the exact
      toolchain to install, for example:

        rustup install <version>-<your-target-triple>

      Homebrew installs only `rustup`; the toolchain itself lives in ~/.rustup, may be
      shared with other Rust projects, and is left in place by `brew uninstall verus`.
      To reclaim that space later:

        rustup toolchain uninstall <version>-<your-target-triple>
    EOS
  end

  test do
    # The right version landed and stayed addressable from libexec.
    assert_equal version.to_s, (libexec/"version.txt").read.strip

    # With no matching toolchain installed (the case on a clean CI runner), the relocated
    # launcher finds its bundled metadata and reports which toolchain it needs. `|| true`
    # keeps the assertion independent of the exact exit code, which on this path is passed
    # through from rustup rather than chosen by verus.
    output = shell_output("#{bin}/verus --version 2>&1 || true")
    assert_match "toolchain", output
  end
end
