#!/usr/bin/env bash
#
# generate-formula.sh — regenerate Formula/verus.rb for a given Verus release.
#
# Usage:
#   scripts/generate-formula.sh <tag-or-version> [artifact-dir] > Formula/verus.rb
#
#   <tag-or-version>   e.g. "release/0.2026.05.24.ecee80a" or "0.2026.05.24.ecee80a"
#   [artifact-dir]     optional directory holding the release .zip files that were
#                      just built. When a matching zip is present there it is hashed
#                      locally (the release-integrated path); otherwise the asset is
#                      downloaded from the GitHub release (the scheduled-bump path).
#
# This script is the ONE place formula logic lives. Formula/verus.rb is generated
# output — never hand-edit it; edit this template and re-run. The only thing that
# changes per release is data (version + per-platform sha256), and that data is
# produced here, from the exact artifacts, with no human in the loop.
#
# Add a new platform target (e.g. arm64-linux) by adding it to PLATFORMS below and
# adding the matching url/sha256 pair to the template. That is the only manual touch
# a new target requires.
set -euo pipefail

REPO="verus-lang/verus"
TAG="${1:?usage: generate-formula.sh <tag-or-version> [artifact-dir]}"
ARTIFACT_DIR="${2:-}"
VERSION="${TAG#release/}"   # strip the "release/" tag prefix if present

# Asset arch/os tokens that map to Homebrew platform branches.
PLATFORMS="arm64-macos x86-macos x86-linux"

sha256_of() {  # <path> -> hex digest
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

url_for() {  # <token> -> download URL
  printf 'https://github.com/%s/releases/download/release/%s/verus-%s-%s.zip' \
    "$REPO" "$VERSION" "$VERSION" "$1"
}

sha_for() {  # <token> -> sha256, from a local artifact if available, else downloaded
  local token="$1" file tmp
  file="verus-${VERSION}-${token}.zip"
  if [ -n "$ARTIFACT_DIR" ] && [ -f "$ARTIFACT_DIR/$file" ]; then
    sha256_of "$ARTIFACT_DIR/$file"
  else
    tmp="$(mktemp)"
    curl -fsSL "$(url_for "$token")" -o "$tmp"
    sha256_of "$tmp"
    rm -f "$tmp"
  fi
}

# Fail loudly if any expected target is missing for this release. When wired into the
# upstream release workflow this runs AFTER the release is published, so a failure here
# shows a red check to investigate without ever rolling back or blocking the release.
SHA_ARM_MAC="$(sha_for arm64-macos)"
SHA_X86_MAC="$(sha_for x86-macos)"
SHA_X86_LINUX="$(sha_for x86-linux)"

# Quoted heredoc: the Ruby below is emitted verbatim (no shell interpolation, so
# Ruby's own #{...} and the livecheck regex survive intact). Data is substituted by
# the sed pass that follows.
template() {
cat <<'RUBY'
class Verus < Formula
  desc "Tool to verify correctness of code written in Rust"
  homepage "https://github.com/verus-lang/verus"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
    regex(%r{release/v?(\d+(?:\.\d+)+\.[0-9a-f]+)}i)
  end

  depends_on "rustup"

  # Verus ships prebuilt, per-platform archives; this formula is a pure relocation
  # layer — nothing is compiled at install time. GENERATED by scripts/generate-formula.sh,
  # do not edit by hand.
  on_macos do
    on_arm do
      url "@@URL_ARM_MAC@@"
      sha256 "@@SHA_ARM_MAC@@"
    end
    on_intel do
      url "@@URL_X86_MAC@@"
      sha256 "@@SHA_X86_MAC@@"
    end
  end

  on_linux do
    on_intel do
      url "@@URL_X86_LINUX@@"
      sha256 "@@SHA_X86_LINUX@@"
    end
  end

  def install
    # The archive expands to a single verus-<arch>-<os>/ directory, which Homebrew
    # descends into automatically — so Dir["*"] is its contents: the `verus` launcher,
    # the `z3` solver, the `vstd` standard library and the rest of the runtime. `verus`
    # locates those relative to its own path, so the whole tree must stay together;
    # we keep it in libexec and expose only the launchers via exec scripts (this also
    # avoids leaking a generic `z3` into bin and clashing with the z3 formula).
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"verus"
    bin.write_exec_script libexec/"cargo-verus"
  end

  def caveats
    <<~EOS
      Verus needs a specific rustup-managed Rust toolchain at runtime. It is not
      bundled and not installed by Homebrew. Run `verus` once and it prints the exact
      toolchain to install, for example:

        rustup install <version>-<your-target-triple>

      Homebrew installs only `rustup`; the toolchain itself lives in ~/.rustup, may be
      shared with other Rust projects, and is left in place by `brew uninstall verus`.
      To reclaim that space later:

        rustup toolchain uninstall <version>-<your-target-triple>
    EOS
  end

  test do
    # The right version landed and stayed addressable from libexec.
    assert_equal version.to_s, (libexec/"version.txt").read.strip

    # With no matching toolchain installed, the relocated launcher finds its own
    # bundled metadata, reports which toolchain it needs, and exits non-zero.
    output = shell_output("#{bin}/verus --version 2>&1", 1)
    assert_match "toolchain", output
  end
end
RUBY
}

template | sed \
  -e "s|@@URL_ARM_MAC@@|$(url_for arm64-macos)|g" \
  -e "s|@@SHA_ARM_MAC@@|${SHA_ARM_MAC}|g" \
  -e "s|@@URL_X86_MAC@@|$(url_for x86-macos)|g" \
  -e "s|@@SHA_X86_MAC@@|${SHA_X86_MAC}|g" \
  -e "s|@@URL_X86_LINUX@@|$(url_for x86-linux)|g" \
  -e "s|@@SHA_X86_LINUX@@|${SHA_X86_LINUX}|g"
